###
GET http://localhost:3333/farmacias

###
POST http://localhost:3333/farmacias
Content-Type: application/json

{
  "name": "Farmautil",
  "urllogo": "farmacia-farmautil-centro.jpg",
  "phone": "(45) 3541-1414",
  "whatsapp": "+554535411414",
  "street": "Rua Primeiro de Maio, 610",
  "city": "Santa Terezinha de Itaipu",
  "zipcode": 85875000,
  "neighborhood": "Centro",
  "lat": "-25.441324",
  "lng": "-54.4020118,17z",
  "email": "farmautilbr@gmail.com"
}