-- AlterTable
ALTER TABLE "farmacias" ALTER COLUMN "createAt" DROP DEFAULT,
ALTER COLUMN "updateAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "plantoes" ALTER COLUMN "createAt" DROP DEFAULT,
ALTER COLUMN "updateAt" DROP DEFAULT;
